name: Run Maven Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Run tests
      run: mvn -B test -Dgroups=release
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
