name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    - name: Start ChromeDriver
      run:  |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests with group 'release'
      run: mvn test -Dgroups=release
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
