name: Run Tests

on:
  push:
    branches: 
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    - name: Start ChromeDriver
      run: |
        setx DISPLAY :99
        setx CHROMEDRIVER_OPTS "--remote-debugging-port=9222 --disable-dev-shm-usage" # Add this line
        chromedriver %CHROMEDRIVER_OPTS% --url-base=/wd/hub & # Modify this line
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: '124'
        install-dependencies: true
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run tests
      run: mvn clean test -Dgroups=release
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
