name: Run Tests on ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: '124'
        install-dependencies: true
    - name: Move Chrome to /usr/bin
      run: sudo mv /usr/bin/google-chrome /usr/bin/google-chrome-old && sudo ln -s /opt/google/chrome/google-chrome /usr/bin/google-chrome
    - name: Start ChromeDriver
      run: |
        chromedriver --url-base=/wd/hub --port=4444 & sleep 3
    - name: check chrome driver
      run: pgrep chromedriver
    - name: Run tests
      run: mvn clean test -Dgroups=release -Dbrowser=chrome -Dchrome.options="--headless,--no-sandbox,--disable-dev-shm-usage"
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
